version: 1.0

superpick: false ## superpick allows instantenous block breaking
superpick_item: 284 ## Gold shovel

maxLayers: 10 ## Maximum amount of layers a spleef can have
maxRegionSize: 20000 ## Maximum size for each spleef layer
