configVersion: 2.0
## This should be places in the plugin directory
## for more help configuring see the wiki
## https://github.com/alkarinv/BattleArena/wiki
## Change this file to customize your event

ESpleef:
    enabled: true
    prefix: "&b[eSpleef]&e"
    command: espleef
    type: ESpleef
    database: eSpleef # or delete if you dont want wins/losses/top, needs BattleTracker
    joinType: JoinPhase
    victoryCondition: LastManStanding
    nTeams: 2+
    teamSize: 1
    defaults:
        options: [woolTeams]
    preReqs:
        options: []
    onEnter:
        options: [storeAll]
    onLeave:
        options: [restoreAll]
    onJoin:
        options: [teleportIn, pvpOff, hunger=20]
    onOpen:
        options: [pvpOff, blockBreakOff]
    onPrestart:
        options: [pvpOff, deEnchant, blockBreakOff]
    onStart:
        options: [pvpOff, hunger=20, blockBreakOn]
    onSpawn:
        options: [giveItems, health=20, hunger=20]
        items: # ignored if options doesnt have "giveItems"
        - diamond_spade: 1
        - shear: 1
    onDeath:
        options: [clearInventory]
    onComplete:
        options: [teleportOut, clearInventory]
    onVictory:
        options: [invincible]
    winner:
        options: [health=20, hunger=20]