name: ${project.name}
version: ${project.version}

main: mc.arena.spleef.ArenaSpleef
depend: [BattleArena, WorldGuard, WorldEdit]
authors: [alkarin_v]

commands:
   spleef:
   espleef:
       aliases: [eventspleef]
