name: ArenaSpleef
main: mc.arena.spleef.ArenaSpleef
version: 1.4.4
depend: [BattleArena, WorldGuard, WorldEdit]
authors: [alkarin_v]

commands:
   spleef:
   espleef:
       aliases: [eventspleef]
   