Spleef:
  name: Spleef
  command: Spleef
  prefix: '&b[Spleef]&e'
  signDisplayName: '&b[Spleef]&e'
  gameSize:
    nTeams: 2+
    teamSize: '1'
  nLives: '1'
  victoryCondition: LASTMANSTANDING
  tracking:
    database: Spleef
    rated: true
    useTrackerMessages: false
  arenaType: Spleef
  arenaClass: SpleefArena
  defaults:
    options:
    - woolTeams
  onEnter:
    options:
    - STOREALL
  onLeave:
    options:
    - RESTOREALL
  preReqs:
    options:
    - clearInventory
  onStart:
    options:
    - teleportIn
    - pvpOff
  onVictory:
    options:
    - invincible
  onComplete:
    options:
    - teleportOut
    - clearInventory
  onSpawn:
    giveItems:
    - DIAMOND_SPADE 1
    options:
    - health=20.0
    - hunger=20
    - deEnchant
  onDeath:
    options:
    - clearInventory
  winners:
    options:
    - health=20.0
    - hunger=20
