# -----------------
# Main configuration for ArenaSpleef
#
# Documentation: https://docs.battleplugins.org/books/additional-gamemodes/chapter/spleef
# Support: https://discord.gg/tMVPVJf
# GitHub: https://github.com/BattlePlugins/ArenaSpleef
# -----------------
config-version: 2.0 # The config version, do not change!

# The shovels to use for Spleef.
shovels:
  classic: diamond_shovel{display-name=<yellow>Spleef Shovel}
  super-shovel: golden_shovel{display-name=<aqua><bold>Super Spleef Shovel;enchantments=[unbreaking:10,efficiency:5]}
  egg-cannon: netherite_shovel{display-name=<gold><bold>Egg Cannon;enchantments=[unbreaking:10,efficiency:5];item-flags=[hide_enchants]}
  bow: bow{display-name=<red><bold>Fire Bow;enchantments=[unbreaking:10,infinity:1,flame:1]}