# -----------------
# Main configuration for ArenaSpleef
#
# Documentation: https://docs.battleplugins.org/books/additional-gamemodes/chapter/spleef
# Support: https://discord.gg/tMVPVJf
# GitHub: https://github.com/BattlePlugins/ArenaSpleef
# -----------------
config-version: 2.0 # The config version, do not change!

# The shovels to use for Spleef.
shovels:
  classic: diamond_shovel{display-name=Spleef Shovel}
  super-shovel: golden_shovel{display-name=Super Spleef Shovel;enchantments=[unbreaking:10,efficiency:5]}