name: ArenaSpleef
main: org.battleplugins.arena.spleef.ArenaSpleef
version: ${version}
description: A Spleef mode for BattleArena.
author: BattlePlugins
website: https://battleplugins.org
api-version: 1.19
depend: [BattleArena]
softdepend: [WorldEdit]